### ISSUE TITLE
Create an Installation Script

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#145]

**Comment by sdc50** [comment]
With the move to conda I see two levels for this:

1. We package release versions as a conda package and then installing becomes trivial. A simple bash script could be used to set up an environment install the Tethys package and then walk the user through configuring the settings file.
2. A bash script to pull the development branch would also be possible. It would be especially easy if we set up the Tethys Database from conda rather than using the dockers.

**Comment by swainn** [comment]
Perhaps we could install using a custom conda installer. No script required. Technically, for development installations, you don't really need to change any settings. We could even probably have it create a default super user.
