### ISSUE TITLE
Make dev the default branch

### ISSUE THREAD

**Issue by sdc50** [tethysplatform/tethys#230]
It would be really nice for pull requests to have dev be the default branch in this repo. I'm just not sure how that would effect RTD.

**Comment by swainn** [comment]
@sdc50 would you care to be more specific about how changing the default branch to dev would be beneficial?

Here are the docs for ReadTheDocs (makes my head hurt) on versions: https://docs.readthedocs.io/en/latest/versions.html#versions

Looks like they intend latest to be up to date with latest development while stable is supposed to be latest tagged release. So... if we change our default branch to dev, we'd be better aligned with how RTD intends those tags to be used. However, it will mean updating our website and a few other places (like the gizmo showcase) to point at the stable docs rather than the latest docs. Or even better we have those links point at latest in the dev branch and stable in the master branch. Thoughts?

**Comment by sdc50** [comment]
I'm moving toward the philosophy that no one should commit directly to the main repository, which is why I've forked it and have been issuing pull requests. This facilitates code review for everything that goes into the project. Pull requests, by default, are set to merge to the master branch. Since almost all pull requests should be going to the dev branch I think it would make it easier to have the dev branch be the default.

**Comment by swainn** [comment]
I like this philosophy of having everyone fork and issues pull requests. I went ahead and made a fork myself. :D I think all we need to do to move forward with this is identify places in the docs that reference the "latest" version of the docs and change it to "stable". This would include tethysplatform.org. I guess another way to do it would be to make the change and then fix what breaks.

**Comment by snowman2** [comment]
To prevent confusion, add in the documentation for release installation:

git clone --branch=1.4.0 https://github.com/tethysplatform/tethys.git
