### ISSUE TITLE
Dependencies in Release

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#438]
Issue #436 reminded me of the risks of having a release version with open-ended dependencies. However, @sdc50 also reminded me that constraining dependencies too much causes other issues for app developers wanting to install dependencies for their apps (for an example of what happens when dependencies are too restrictive see #422). Before the release of version 3.0, we need to determine how to handle dependencies in Tethys. Having dependencies frozen permanently creates another issue of relying on outdated versions of packages.

I propose something along the lines of the following:

* Keep dependencies open in the development version of Tethys to allow testing future versions with updated dependencies
* Freeze version of all dependencies to the latest minor version at the time of release for release installations only.

If this is the approach we decide to take, what's the best way to enforce it?

**Comment by john3641** [comment]
As the noob who posted Issue #436, I like your proposal of freezing "tothe latest minor version" for release installations. 

I'll throw this in for consideration for 3.0, as something maybe to consider from an outsider's view:  I have experience using R and other software, and when I was introduced to tethys the first thing I saw after entering the homepage was a "master" version.  I assumed this was a version to fall back on, a very stable version.  I suppose if I had seen that there is a "release" version at that time, I might have questioned that assumption.  You have since made sure that the home page directs to "stable" version, the "release" version.  But still, the terms "release" vs "master" don't seem very self-revealing to me.  What is being "released"?  And "master" for what?  There might be a very good rationale for using "release" and "master", but as an outsider I'm left thinking, 'why not just call the stable version "stable"?'

**Comment by swainn** [comment]
From conversion between @sdc50 and @swainn:
* Lock dependencies right before release
    * Build fresh dev and lock to versions it resolves to
* Provide documentation to install release version with unlocked dependencies as fallback.

**Comment by swainn** [comment]
Potentially generate the meta.yml with a gen command.

**Comment by swainn** [comment]
Addresed in PR #490
