### ISSUE TITLE
Unable to install Tethys platform on Windows

### ISSUE THREAD

**Issue by ashishiit** [tethysplatform/tethys#448]
I followed the installation steps for Windows as mentioned in the following link:
http://docs.tethysplatform.org/en/stable/installation/windows.html

I performed the steps 1(a) , 1(b) and double clicked the install_tethys.bat.

Actual result : In the C drive, a tethys folder is created which only contains the miniconda folder.

Expected result : tethys_cmd.bat file should also be there in the tethys folder as per the installation instruction.

**Comment by swainn** [comment]
@ashishiit installation of Tethys Platform on Windows has always been somewhat experimental. We haven't invested the resources to keep that script up-to-date, because we are in the process of changing to installing Tethys as a conda package in our next release. The conda package isn't quite there for Windows yet.

You can attempt installing the conda package periodically from our development version using this command:

`conda create -n tethys -c tethys/label/dev -c tethysplatform -c conda-forge tethysplatform`

Full installation instructions are here: http://docs.tethysplatform.org/en/latest/installation.html

In the mean time, it should work on Mac or Linux.

**Comment by ashishiit** [comment]
@swainn Thanks. I installed virtualbox and ubuntu on my Windows machine which helped to solve the issue.
