### ISSUE TITLE
conda install tethys  on ubuntu      error

### ISSUE THREAD

**Issue by gaoxiang123456789** [tethysplatform/tethys#452]
(base) gaoxiang@gaoxiang-VirtualBox:~$ conda install -c tethysplatform/label/dev tethysplatform
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - tethysplatform -> channels -> asgiref
  - tethysplatform -> channels -> daphne -> autobahn
  - tethysplatform -> distro
  - tethysplatform -> django-bootstrap3
  - tethysplatform -> django-filter
  - tethysplatform -> django-guardian
  - tethysplatform -> django-model-utils
  - tethysplatform -> djangorestframework
  - tethysplatform -> geoalchemy2
  - tethysplatform -> hs_restclient
  - tethysplatform -> requests-mock
  - tethysplatform -> social-auth-app-django

Current channels:

  - https://conda.anaconda.org/tethysplatform/label/dev/linux-64
  - https://conda.anaconda.org/tethysplatform/label/dev/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by sdc50** [comment]
Not all of the dependencies of tethysplatform are available on the tethysplatform conda channel, so you need to also include the conda-forge channel when installing tethysplatform.

```bash
conda install -c tethysplatform/label/dev -c conda-forge tethysplatform
```

It looks like you are trying to install tethysplatform into your ``base`` conda environment. I would not recommend that. You can create a new conda environment and install tethysplatform with this command:

```bash
conda create -n tethys -c tethysplatform/label/dev -c conda-forge tethysplatform
```

I should also note that we are close to releasing Tethys 3.0 at which point you should use `-c tethysplatform` rather than `-c tethysplatform/label/dev`.
