### ISSUE TITLE
Many Tethys Conda Dependencies are Still Released on Tethys Dev Label

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#517]
* These need to be released either on our main label or conda-forge.

**Comment by sdc50** [comment]
I've just moved all but one of the packages over to the main channel. There are 5 packages that have newer releases since I built them, so I am planning to build the newer versions of those.

I've discovered one challenge. I can't access the details page for the `channels` package, because the url pattern that the Anaconda Cloud site uses is `anaconda.org/<organization_name>/<package_name>`. However, there is a special case for `anaconda.org/<organization_name>/channels` which is an alias for the labels page for the organization. In other words, the details page for the channels package happens to have the same url as another page, so it cannot be accessed. I may need to change the name of the package to `django-channels` or something to get it to work.

**Comment by swainn** [comment]
@sdc50 any update on this? I see a package called django-channels now and as far as I can tell, all packages have been moved to main.

**Comment by sdc50** [comment]
Yes, all packages have been moved to main. So we are good to go there. I built a newer version of `channels` and pushed it to dev and main (which you can do when first uploading from the command line). I also build the same package as `django-channels`. I'm still undecided about what to do on this as far as Tethys's dependencies go, but it should work for now unchanged.
