### ISSUE TITLE
Job logs work while job is running but not after job is done [bug]

### ISSUE THREAD

**Issue by msouff** [tethysplatform/tethys#617]
Once the job is completed, an exception is thrown when trying to access the logs from the jobs table.

@nathan was able to reproduce it. @sdc50 have you seen this?

**Comment by swainn** [comment]
We get the generic error message in the log dialog (note the Job ID is undefined):

![image](https://user-images.githubusercontent.com/5123221/99561898-b55b1800-2984-11eb-9d7a-05b6ae3e6d04.png)

Here is what is being logged to the console when this error occurs:

```bash
INFO:condorpy:Calling function: <function HTCondorObjectBase._execute at 0x7f9ee31ab170> with args=(['cat', 'finalize/logs/*.err'],)
INFO:condorpy:Saved cwd: /home/steem/.tethys/tethys/
INFO:condorpy:Changing working directory to: /home/steem/aquadev/tethysapp-steem/tethysapp/steem/workspaces/user_workspaces/admin/00986e67-460d-4713-a020-3e2bf3d68481/c06fff5c-e87f-433d-bcc9-a3df82697b2a/Run_Hydraulic_Model
INFO:condorpy:Executing remote command cat finalize/logs/*.err
INFO:condorpy:Execute results - out: None, err: The command 'cd 9e7fb9db645748e8b06baeebd94f9a9f && cat finalize/logs/*.err' failed on host 'localhost':

bash: line 0: cd: 9e7fb9db645748e8b06baeebd94f9a9f: No such file or directory

INFO:condorpy:Restored working directory to: /home/steem/.tethys/tethys/
ERROR:tethys.tethys_gizmos.views.jobs_table:The following error occurred when retrieving log content for log 12 in job finalize error: 'NoneType' object has no attribute 'replace'
```

**Comment by swainn** [comment]
I've looked into this and I know why it is occurring, but I'm not sure what to do about it yet.

The implementation for `_get_logs()` in `CondorBase` is the following:

```python
    def _get_logs(self):
        """
        Get logs contents for condor job.
        """
        log_files = self._log_files()
        log_contents = self._get_logs_from_remote(log_files)
        # Check to see if log_contents are empty. If it's empty, the job on the condor machine might get removed.
        # We will try to get from the workspace if this is the case.
        log_has_content = self._check_log_has_content(log_contents)
        if not log_has_content:
            log_contents = self._get_logs_from_workspace(log_files)
        return log_contents
```

Notice the `_get_logs_from_remote()` and `_get_logs_from_workspace()`. When a job has finished running, the files are deleted on the remote worker and copied to the job workspace, which is usually in one of the app's workspaces. At this point calls to the remote to get the logs will fail, so we need to get them from the job workspaces. The problem is that the logic in `_check_log_has_content()` is unable to detect when it's time to switch. Here's the implementation:

```python
    @staticmethod
    def _check_log_has_content(log_contents):
        """
        Return True if log content is not empty.
        """
        for key, value in log_contents.items():
            if isinstance(value, dict):
                for child_value in value.values():
                    if child_value:
                        return True
            else:
                if value:
                    return True
        return False
```


The `log_contents` variable no longer contains the actual contents of the logs but instead has partial functions that can be used to get the contents lazily. Thus the `value` is never a `dict` and is always truthy.

I have manually forced `log_has_content` to be `False` in the debugger so that it calls `_get_logs_from_workspace()` and it works. So we just need a better check to inform `_get_logs()` when to get the logs locally. We could check for callables and execute them to restore the original functionality, but this would defeat the purpose of having them in the first place and degrade performance. Perhaps we could key off the job status? i.e.: when it has a terminal status? Thoughts?

**Comment by swainn** [comment]
I just had a thought. We could refactor `_check_log_has_content()` the check for the job directory on the remote or local to decide where to get logs. I think that's probably the easiest way to handle it.

**Comment by sdc50** [comment]
@swainn, @msouff is it safe to assume that if the local log files exist then it should read from there? Is there ever a case where it would transfer the log files mid-job?

**Comment by swainn** [comment]
> @swainn, @msouff is it safe to assume that if the local log files exist then it should read from there? Is there ever a case where it would transfer the log files mid-job?

Seems like a safe assumption.

**Comment by swainn** [comment]
@sdc50, @msouff tested this and from what I can tell, this is a step back. The logs don't work at all now, when the job is running or when the job is finished.

**Comment by swainn** [comment]
> @sdc50, @msouff tested this and from what I can tell, this is a step back. The logs don't work at all now, when the job is running or when the job is finished.

From what I remember `_get_logs_from_remote()` and `_get_logs_from_workspace()` worked as they were. The issue was that it uses `_check_log_has_content()` to determine which method to check. This broke when you swapped out `dict` for `partials`.
