### ISSUE TITLE
Connection refused on port 8000

### ISSUE THREAD

**Issue by mlandsfeld** [tethysplatform/tethys#692]
I am moving my Tethys app to a Linux server and I keep getting a connection refused on port 8000. I can run the portal via localhost but not from outside of the VM. I have run "tethys settings -- set ALLOWED_HOSTS..." but still can not make a connection to the IP address or domain name. Is there anything else that needs to be done?
Thanks!

**Comment by msouff** [comment]
I would post this on discussions since this seems to be a machine specific problem rather than a general issue.

Things to try:

I would start by checking that port 8000 is not being used by other software. You can regenerate settings by using the "tethys gen" command with the "--overwrite" option, then specify the "tethys_port" parameter and set it to something else, like 8080 to see if that works.
