### ISSUE TITLE
Permission denial message not showing up in Tethys 4

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#802]
Steps to reproduce:
1. Install the Dam Inventory solution with the permissions implemented (Quotas/Adanced)
2. Update the app for Tethys 4 (if needed) with controller decorator
3. Access the app with a non-staff user and without permissions
4. Click on the Add Dam button (either one)

Behavior:
Page refreshes and does not allow user to go to the add dam page as expected, but the permission denied message that should be displayed in an alert message box is not displayed.

Expected Behavior:
Permission denied message should be displayed

**Comment by swainn** [comment]
This issue discusses how to post message on redirect: https://stackoverflow.com/questions/14999134/how-to-pass-a-message-from-httpresponseredirect-in-django

**Comment by swainn** [comment]
This is where it is handled: https://github.com/tethysplatform/tethys/blob/master/tethys_apps/decorators.py#L162

**Comment by sdc50** [comment]
So the issue here was with the new controller decorator. The default message was only used if the `message` kwarg was not passed at all. The controller decorator would always pass the `message` kwarg, but it's default was `None`. So rather than having the default message, it the message value would jsut be `None`.
