### ISSUE TITLE
password authentication error, postgis.control missing

### ISSUE THREAD

**Issue by john3641** [tethysplatform/tethys#832]
Hello.
I seem to be unable to establish a Spatial Persistent Store for my apps.  I installed the Developer Installation of Tethys 3.4.1 last summer, then recently upgraded to 3.4.2 using 
conda install -c tethysplatform -c conda-forge tethys-platform=3.*
and then migrated databases using 
tethys db migrate
with no error showing.
I have the PostGIS/Database, Geoserver, and 52 North WPS dockers installed and running.  I also have pgAdmin4 installed.

One on my apps for which I can't seem to develop a Spatial Persistent Store is the "Advanced Solution" of dam_inventory tutorial.  IN thIt is running fine, but in the tutorial there is no Spatial Persistent Store  (i.e., no "spatial = True" argument in the PersistentStoreDatabaseSetting function of the app.py file).  If I add that argument, it doesn't seem to enable the spatial (PostGIS) component.  For example, when I go to pgAdmin4, I see the "dam" table, but if I try to add a "geometry" column, 'geometry' does not appear in the list of Data Type options.  (And I did run the 'syncstores' command.)  The dam_inventory app still runs as expected, because it requires no Spatial Persistent Store.  I noticed, however, that my PostGIS/Database docker is working at port 5435, while in the Tethys Portal Admin page, I had set the port for the Persistent Store to 5436.  So, I changed the port from 5436 to 5435.  But this time I get the towards the end of a lengthy list of errors: "FATAL: password authentication failed for user "tethys_super".

I get the same pgAdmin4 behavior and same authentication error for another app (actually, download of glo-vli-master, with localhost substituted for hydropad.org - and, by the way, thanks to the author!).  However, this app actually needs a spatial persistent store.  And if I leave the port at 5436 in the Tethys Portal Admin, even though docker is a 5435, I get an error stating "sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not open extension control file "/home/john/miniconda3/envs/tethys/share/extension/postgis.control".  And when I manually navigate to this folder, I see no file named "postgis.control".

I thought that maybe I need to edit the "portal_config.yml" file,  but I don't see anything in it that contradicts any info that I have provided to through the portal.  It currently appears like this:
version: 1.0
name:
apps: {}
settings:
  SECRET_KEY: (a bunch of letters and numbers that were automaticaly generated here)
site_content: {}

Anyway, I'm stumped.  Your help would be much appreciated.

**Comment by swainn** [comment]
Hey @john3641, sorry you are having trouble. Sounds like there are a few different issues going on here:

1. PostGIS is actually an extension for the PostgreSQL database, which means that it doesn't come installed by default. The error `sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not open extension control file` that you are getting is an indication that you have connected to a PostgreSQL database without PostGIS extension installed.
2. The default PostgreSQL database that is installed in the conda environment when you install Tethys does not have PostGIS installed, unfortunately (the PostGIS conda package causes a lot of issues so we don't include it). This database runs on port 5436 and is controlled through the `tethys db` commands.
3. The PostGIS docker container that is created by the `tethys docker` commands does have PostGIS installed and runs on port 5435, but it doesn't have any of the Tethys database users (e.g. `tethys_super`) set up initially. So if you configure your Persistent Store to try to connect to that database with user tethys_super, you will get the error `FATAL: password authentication failed for user "tethys_super"`.

Solution:

While it is not required that your Tethys Portal and app persistent stores databases use the same database, if you plan to use PostGIS, I'd recommend that you configure Tethys to use the docker PostGIS database instead of the Conda installed database and configure your app persistent stores to also use the Docker database.

1. Stop the conda database by running:

```bash
tethys db stop
```

2. Configure the database settings in your `portal_config.yml` as follows:

```yaml
settings:
  DATABASES:
    default:
      HOST: localhost
      NAME: tethys_platform
      PASSWORD: pass
      PORT: 5435
      USER: tethys_default
```

IMPORTANT: Make sure the `DIR` setting is not set.

3. Run the following command to create the Tethys databases and users:

```bash
PGPASSWORD=mysecretpassword tethys db configure --username tethys_default --password pass --superuser-name tethys_super --superuser-password pass --portal-superuser-name admin  --portal-superuser-pass pass
```

The password `mysecretpassword` is the default password for the PostGIS docker container. If you specified a different password when you created the PostGIS database with `tethys docker init`, use that password instead.

IMPORTANT: The command above is assuming a development environment. For production installations, don't use default or weak passwords like those above! 

4. Start Tethys as normal 

```bash
tethys manage start
```

5. DON'T use the `tethys db` commands to start the database for Tethys anymore. Instead, use `tethys docker start`.

6. After completing the steps above, you should be able to create a spatial persistent store that points at the docker database (port 5435) and use the user `tethys_super`.

Best of luck!

**Comment by john3641** [comment]
Thank you so much, @swainn!   This worked beautifully!
